//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ForeverEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_ForeverEditorTYPE           129
#define IDD_ItemEdit                    130
#define IDD_ItemTypeWeapon              132
#define IDD_ItemTypeArmor               133
#define IDD_ItemTypeConsumable          134
#define IDD_DIALOG1                     138
#define IDD_BuffEdit                    140
#define IDD_SkillEdit                   142
#define IDD_MonsterEdit                 144
#define IDC_ItemList                    1000
#define IDC_ItemType                    1001
#define IDC_ItemName                    1002
#define IDC_ItemSoulBind                1003
#define IDC_ItemLevel                   1005
#define IDC_ItemStackLimit              1006
#define IDC_ItemSellPrice               1008
#define IDC_ItemBuyPrice                1009
#define IDC_AddItem                     1010
#define IDC_ItemTypeMenu                1012
#define IDC_SaveList                    1015
#define IDC_LoadList                    1016
#define IDC_AttrHP                      1017
#define IDC_Quality                     1018
#define IDC_Wield                       1019
#define IDC_AttrMP                      1020
#define IDC_AttrHPMax                   1021
#define IDC_AttrMPMax                   1022
#define IDC_AttrATK                     1023
#define IDC_AttrDEF                     1025
#define IDC_AttrHIT                     1026
#define IDC_AttrCRI                     1027
#define IDC_AttrMATK                    1028
#define IDC_AttrMDEF                    1029
#define IDC_AttrMHIT                    1030
#define IDC_AttrMCRI                    1031
#define IDC_AttrSDEF                    1032
#define IDC_AttrWDEF                    1033
#define IDC_AttrFlee                    1034
#define IDC_AttrMove                    1035
#define IDC_AttrATKSpeed                1036
#define IDC_AttrCasting                 1037
#define IDC_AttrType                    1038
#define IDC_Wear                        1039
#define IDC_AttrSave                    1042
#define IDC_addClass                    1043
#define IDC_Desc                        1064
#define IDC_Effect                      1065
#define IDC_Much                        1066
#define IDC_iconName                    1067
#define IDC_BuffList                    1095
#define IDC_BuffName                    1096
#define IDC_BufficonName                1097
#define IDC_BuffContinued               1098
#define IDC_BuffHarmful                 1099
#define IDC_BuffDesc                    1100
#define IDC_BuffAttrType                1101
#define IDC_BuffAttrHP                  1102
#define IDC_BuffAttrMP                  1103
#define IDC_BuffAttrHPMax               1104
#define IDC_BuffAttrSave                1105
#define IDC_BuffAttrMPMax               1106
#define IDC_BuffAttrATK                 1107
#define IDC_BuffAttrDEF                 1108
#define IDC_BuffAttrHIT                 1109
#define IDC_BuffAttrCRI                 1110
#define IDC_BuffAttrSDEF                1111
#define IDC_BuffAttrFlee                1112
#define IDC_BuffAttrATKSpeed            1113
#define IDC_BuffAttrMATK                1114
#define IDC_BuffAttrMDEF                1115
#define IDC_BuffAttrMHIT                1116
#define IDC_BuffAttrMCRI                1117
#define IDC_BuffAttrWDEF                1118
#define IDC_BuffAttrMove                1119
#define IDC_BuffAttrCasting             1120
#define IDC_AddBuff                     1121
#define IDC_SaveBuff                    1122
#define IDC_LoadBuff                    1123
#define IDC_BuffAttrHPR                 1124
#define IDC_BuffAttrMPR                 1125
#define IDC_SkillList                   1126
#define IDC_SkillType                   1127
#define IDC_SkillLevel                  1128
#define IDC_SkilliconName               1129
#define IDC_SkillName                   1130
#define IDC_SkillDesc                   1132
#define IDC_SkillActionID               1133
#define IDC_SkillCastTime               1134
#define IDC_SkillCoolDown               1135
#define IDC_SkillCastRange              1136
#define IDC_SkillTargetType             1138
#define IDC_SkillBuff                   1139
#define IDC_SkillMotionEffects          1140
#define IDC_SkillTriggerMotion          1141
#define IDC_SkillWeapon                 1142
#define IDC_SkillShield                 1143
#define IDC_SkillAttrType               1144
#define IDC_SkillAttrSave               1145
#define IDC_SkillNew                    1146
#define IDC_SkillSave                   1147
#define IDC_SkillLoad                   1148
#define IDC_SkillAttrHP                 1150
#define IDC_SkillAttrMP                 1151
#define IDC_SkillAttrHPMax              1152
#define IDC_SkillAttrMPMax              1153
#define IDC_SkillAttrATK                1154
#define IDC_SkillAttrDEF                1155
#define IDC_SkillAttrHIT                1156
#define IDC_SkillAttrCRI                1157
#define IDC_SkillAttrSDEF               1158
#define IDC_SkillAttrFlee               1159
#define IDC_SkillAttrATKSpeed           1160
#define IDC_SkillAttrMATK               1163
#define IDC_SkillAttrMDEF               1164
#define IDC_SkillAttrMHIT               1165
#define IDC_SkillAttrMCRI               1166
#define IDC_SkillAttrWDEF               1167
#define IDC_SkillAttrMove               1168
#define IDC_SkillAttrCasting            1169
#define IDC_MonsterList                 1170
#define IDC_SkillCastMP                 1171
#define IDC_MeshName                    1172
#define IDC_EDIT1                       1173

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1174
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
